title: Escuela de Machine Learning
description: Sitio web de la escuela de Machine Learning
url: "https://edithvillegas.github.io"
baseurl: "/escuela-machine-learning"

plugins:
  - jekyll-include-cache

remote_theme: "DigitaleGesellschaft/jekyll-theme-conference@v4.0.2"
